version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
    - pip install --upgrade awscli
  build:
    commands:
    - mvn war:exploded
  post_build:
    commands:
    - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
  - template-export.yml
