version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
    - pip install --upgrade awscli
    - pip install -r webp_converter/requirements.txt
    - pip install -r tests/requirements.txt
  build:
    commands:
    - python -m pytest -s tests/unit/*
  post_build:
    commands:
    - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
  - template-export.yml
